export const DummyPatientList = [
  {
    examinationId: "805605462",
    name: "Daniel Smith",
    examinationList: [
      {
        profileUrl: "/images/고먐미.jpeg",
        hospital: "Seoul National University Hospital",
        doctor: "Dr. Sunghoon Lee",
        date: 20230115,
        result: 55,
        examinationId: "805605462",
      },
      {
        profileUrl: "/images/고먐미.jpeg",
        hospital: "London City Clinic",
        doctor: "Dr. Olivia Brown",
        date: 20230215,
        result: 72,
        examinationId: "805605462",
      },
      {
        profileUrl: "/images/고먐미.jpeg",
        hospital: "New York General Hospital",
        doctor: "Dr. Emily Johnson",
        date: 20230315,
        result: 91,
        examinationId: "805605462",
      },
      {
        profileUrl: "/images/고먐미.jpeg",
        hospital: "Tokyo Medical Center",
        doctor: "Dr. Hiroshi Tanaka",
        date: 20230415,
        result: 77,
        examinationId: "805605462",
      },
      {
        profileUrl: "/images/고먐미.jpeg",
        hospital: "Paris Health Clinic",
        doctor: "Dr. Marie Dupont",
        date: 20230515,
        result: 88,
        examinationId: "805605462",
      },
      {
        profileUrl: "/images/고먐미.jpeg",
        hospital: "Sydney Wellness Center",
        doctor: "Dr. Liam Harris",
        date: 20230615,
        result: 40,
        examinationId: "805605462",
      },
      {
        profileUrl: "/images/고먐미.jpeg",
        hospital: "Berlin Central Hospital",
        doctor: "Dr. Anna Muller",
        date: 20230715,
        result: 79,
        examinationId: "805605462",
      },
      {
        profileUrl: "/images/고먐미.jpeg",
        hospital: "Singapore General Hospital",
        doctor: "Dr. Wei Zhang",
        date: 20230815,
        result: 84,
        examinationId: "805605462",
      },
    ],
  },
  {
    examinationId: "202411041",
    name: "Michael John",
    examinationList: [
      {
        profileUrl: "/images/고먐미.jpeg",
        hospital: "Seoul National University Hospital",
        doctor: "Dr. Minseo Kim",
        date: 20230120,
        result: 92,
        examinationId: "202411041",
      },
      {
        profileUrl: "/images/고먐미.jpeg",
        hospital: "New York General Hospital",
        doctor: "Dr. Emily Johnson",
        date: 20230220,
        result: 81,
        examinationId: "202411041",
      },
      {
        profileUrl: "/images/고먐미.jpeg",
        hospital: "Bangkok International Hospital",
        doctor: "Dr. Nithan Boonchai",
        date: 20230320,
        result: 76,
        examinationId: "202411041",
      },
      {
        profileUrl: "/images/고먐미.jpeg",
        hospital: "London City Clinic",
        doctor: "Dr. Olivia Brown",
        date: 20230420,
        result: 88,
        examinationId: "202411041",
      },
      {
        profileUrl: "/images/고먐미.jpeg",
        hospital: "Tokyo Medical Center",
        doctor: "Dr. Yuki Nakamura",
        date: 20230520,
        result: 85,
        examinationId: "202411041",
      },
      {
        profileUrl: "/images/고먐미.jpeg",
        hospital: "Paris Health Clinic",
        doctor: "Dr. Marie Dupont",
        date: 20230620,
        result: 78,
        examinationId: "202411041",
      },
      {
        profileUrl: "/images/고먐미.jpeg",
        hospital: "Berlin Central Hospital",
        doctor: "Dr. Anna Muller",
        date: 20230720,
        result: 84,
        examinationId: "202411041",
      },
      {
        profileUrl: "/images/고먐미.jpeg",
        hospital: "Singapore General Hospital",
        doctor: "Dr. Wei Zhang",
        date: 20230820,
        result: 80,
        examinationId: "202411041",
      },
    ],
  },
  {
    examinationId: "431216785",
    name: "Emily Davis",
    examinationList: [
      {
        profileUrl: "/images/고먐미.jpeg",
        hospital: "Seoul National University Hospital",
        doctor: "Dr. Sunghoon Lee",
        date: 20230125,
        result: 79,
        examinationId: "431216785",
      },
      {
        profileUrl: "/images/고먐미.jpeg",
        hospital: "London City Clinic",
        doctor: "Dr. Olivia Brown",
        date: 20230225,
        result: 86,
        examinationId: "431216785",
      },
      {
        profileUrl: "/images/고먐미.jpeg",
        hospital: "New York General Hospital",
        doctor: "Dr. Emily Johnson",
        date: 20230325,
        result: 83,
        examinationId: "431216785",
      },
      {
        profileUrl: "/images/고먐미.jpeg",
        hospital: "Tokyo Medical Center",
        doctor: "Dr. Hiroshi Tanaka",
        date: 20230425,
        result: 87,
        examinationId: "431216785",
      },
      {
        profileUrl: "/images/고먐미.jpeg",
        hospital: "Paris Health Clinic",
        doctor: "Dr. Marie Dupont",
        date: 20230525,
        result: 88,
        examinationId: "431216785",
      },
      {
        profileUrl: "/images/고먐미.jpeg",
        hospital: "Sydney Wellness Center",
        doctor: "Dr. Liam Harris",
        date: 20230625,
        result: 84,
        examinationId: "431216785",
      },
      {
        profileUrl: "/images/고먐미.jpeg",
        hospital: "Berlin Central Hospital",
        doctor: "Dr. Anna Muller",
        date: 20230725,
        result: 81,
        examinationId: "431216785",
      },
      {
        profileUrl: "/images/고먐미.jpeg",
        hospital: "Singapore General Hospital",
        doctor: "Dr. Wei Zhang",
        date: 20230825,
        result: 82,
        examinationId: "431216785",
      },
    ],
  },
  {
    examinationId: "789654123",
    name: "Sophia White",
    examinationList: [
      {
        profileUrl: "/images/고먐미.jpeg",
        hospital: "Seoul National University Hospital",
        doctor: "Dr. Minseo Kim",
        date: 20230130,
        result: 84,
        examinationId: "789654123",
      },
      {
        profileUrl: "/images/고먐미.jpeg",
        hospital: "Bangkok International Hospital",
        doctor: "Dr. Nithan Boonchai",
        date: 20230228,
        result: 89,
        examinationId: "789654123",
      },
      {
        profileUrl: "/images/고먐미.jpeg",
        hospital: "London City Clinic",
        doctor: "Dr. Olivia Brown",
        date: 20230330,
        result: 82,
        examinationId: "789654123",
      },
      {
        profileUrl: "/images/고먐미.jpeg",
        hospital: "Tokyo Medical Center",
        doctor: "Dr. Yuki Nakamura",
        date: 20230430,
        result: 85,
        examinationId: "789654123",
      },
      {
        profileUrl: "/images/고먐미.jpeg",
        hospital: "Paris Health Clinic",
        doctor: "Dr. Marie Dupont",
        date: 20230530,
        result: 87,
        examinationId: "789654123",
      },
      {
        profileUrl: "/images/고먐미.jpeg",
        hospital: "Sydney Wellness Center",
        doctor: "Dr. Liam Harris",
        date: 20230630,
        result: 88,
        examinationId: "789654123",
      },
      {
        profileUrl: "/images/고먐미.jpeg",
        hospital: "Berlin Central Hospital",
        doctor: "Dr. Anna Muller",
        date: 20230730,
        result: 80,
        examinationId: "789654123",
      },
      {
        profileUrl: "/images/고먐미.jpeg",
        hospital: "Singapore General Hospital",
        doctor: "Dr. Wei Zhang",
        date: 20230830,
        result: 79,
        examinationId: "789654123",
      },
    ],
  },
  {
    examinationId: "123456789",
    name: "Liam Brown",
    examinationList: [
      {
        profileUrl: "/images/고먐미.jpeg",
        hospital: "Seoul National University Hospital",
        doctor: "Dr. Sunghoon Lee",
        date: 20230110,
        result: 78,
        examinationId: "123456789",
      },
      {
        profileUrl: "/images/고먐미.jpeg",
        hospital: "London City Clinic",
        doctor: "Dr. Olivia Brown",
        date: 20230210,
        result: 80,
        examinationId: "123456789",
      },
      {
        profileUrl: "/images/고먐미.jpeg",
        hospital: "New York General Hospital",
        doctor: "Dr. Emily Johnson",
        date: 20230310,
        result: 85,
        examinationId: "123456789",
      },
      {
        profileUrl: "/images/고먐미.jpeg",
        hospital: "Tokyo Medical Center",
        doctor: "Dr. Hiroshi Tanaka",
        date: 20230410,
        result: 90,
        examinationId: "123456789",
      },
    ],
  },
];
