import { v4 as uuidv4 } from "uuid";

import { PageData } from "types/componenttype";

export const initialPageData: { [key: string]: PageData } = {
  김모아202411041: {
    imageSet: [
      // { id: uuidv4(), x: 0, y: 0, width: 100, height: 100, url: "/images/고먐미.jpeg" }
    ],
    divSet: [{ id: uuidv4(), x: 11, y: 90, width: 755, height: 3, color: "black" }],
    tableSet: [
      // {
      //   id: uuidv4(),
      //   x: 200,
      //   y: 200,
      //   width: 300,
      //   height: 200,
      //   data: [
      //     {
      //       row: 1,
      //       cells: [
      //         { col: 1, content: "하 참" },
      //         { col: 2, content: "Cell 1-2" },
      //         { col: 3, content: "Cell 1-3" },
      //       ],
      //     },
      //     {
      //       row: 2,
      //       cells: [
      //         { col: 1, content: "Cell 2-1" },
      //         { col: 2, content: "Cell 2-2" },
      //         { col: 3, content: "Cell 2-3" },
      //       ],
      //     },
      //     {
      //       row: 3,
      //       cells: [
      //         { col: 1, content: "Cell 3-1" },
      //         { col: 2, content: "Cell 3-2" },
      //         { col: 3, content: "Cell 3-3" },
      //       ],
      //     },
      //   ],
      //   rows: 3,
      //   columns: 3,
      // },
    ],
    textareaSet: [
      {
        id: uuidv4(),
        x: 50,
        y: 60,
        width: 85,
        height: 30,
        placeholder: "Enter text",
        underline: true,
        content: "종합검진",
      },
      {
        id: uuidv4(),
        x: 195,
        y: 60,
        width: 155,
        height: 30,
        placeholder: "Enter text",
        underline: true,
        content: "등록번호 01814444",
      },
      {
        id: uuidv4(),
        x: 430,
        y: 60,
        width: 130,
        height: 30,
        placeholder: "Enter text",
        underline: true,
        content: "일자 2024.05.12",
      },
      {
        id: uuidv4(),
        x: 650,
        y: 60,
        width: 120,
        height: 30,
        placeholder: "Enter text",
        underline: true,
        content: "성명 김모아",
      },
      {
        id: uuidv4(),
        x: 55,
        y: 110,
        width: 705,
        height: 70,
        placeholder: "Enter text",
        underline: true,
        content:
          "[신체계측]\n과체중입니다. 고혈압, 당뇨병, 지방간, 관절염, 심혈관 질환 및 악성 질환의 위험성이 증가합니다. 식이 조절 및 운동으로 체중 및 체지방을 감량하시기 바랍니다.",
      },
      {
        id: uuidv4(),
        x: 55,
        y: 190,
        width: 650,
        height: 70,
        placeholder: "Enter text",
        underline: true,
        content:
          "[허리둘레]\n복부 비만입니다. 복부내장지방 감량을 위해 지속적인 식이 조절 및 운동으로 관리하시길 바랍니다.",
      },
      {
        id: uuidv4(),
        x: 55,
        y: 270,
        width: 630,
        height: 72,
        placeholder: "Enter text",
        underline: true,
        content:
          "[혈압 측정 - 저혈압]\n혈압이 낮게 측정되었습니다. 어지러움 등의 증상이 있을 경우 심장내과에서 진료를 받으시길 바랍니다.",
      },
      {
        id: uuidv4(),
        x: 55,
        y: 350,
        width: 190,
        height: 240,
        placeholder: "Enter text",
        underline: true,
        content:
          "[청력 검사 - 정상]\n\n[폐기능 검사 - 정상]\n\n[시력 검사 - 정상]\n\n[안압 검사 - 정상]\n\n[안저 검사 - 정상]\n\n[혈당 검사 - 정상]",
      },
      {
        id: uuidv4(),
        x: 55,
        y: 600,
        width: 630,
        height: 90,
        placeholder: "Enter text",
        underline: true,
        content:
          "[콜레스테롤 검사 - 이상지질혈증]\n이상지질혈증은 동맥경화증, 고혈압, 뇌혈관질환, 허혈성 심질환 등의 위험 요인이 됩니다. 저지방 식이, 운동, 적정 체중 유지, 금주 및 금연과 같은 생활 습관의 개선이 필요하며 향후 약물 치료가 필요할 수 있습니다. 상담을 원하시면 내분비내과 진료를 받으시기 바랍니다.",
      },
      {
        id: uuidv4(),
        x: 55,
        y: 700,
        width: 630,
        height: 50,
        placeholder: "Enter text",
        underline: true,
        content: "[간기능 검사]\n간 기능 검사상 이상 소견은 없습니다",
      },
      {
        id: uuidv4(),
        x: 55,
        y: 760,
        width: 630,
        height: 60,
        placeholder: "Enter text",
        underline: true,
        content:
          "[간염 검사]\n- A형 감염 항체 양성으로, A형간염 예방접종은 필요가 없습니다. \n- B형 감염 항체 양성으로, A형간염 예방접종은 필요가 없습니다",
      },
      {
        id: uuidv4(),
        x: 55,
        y: 840,
        width: 630,
        height: 60,
        placeholder: "Enter text",
        underline: true,
        content:
          "[신장 기능, 기타 전해질 검사]\n전해질검사 결과 인산염(P) 수치가 높습니다. 신장 질환, 과다한 인 섭취, 과다한 칼슘 배출, 비타민 D 중독 등의 원인이 있을 수 있습니다. 재검사 또는 내과 진료를 받으시기 바랍니다",
      },
      {
        id: uuidv4(),
        x: 55,
        y: 920,
        width: 630,
        height: 40,
        placeholder: "Enter text",
        underline: true,
        content: "[갑상선 기능 검사]\n- 갑상선 기능 검사상 특별한 이상소견은 없습니다.",
      },
      {
        id: uuidv4(),
        x: 55,
        y: 980,
        width: 630,
        height: 40,
        placeholder: "Enter text",
        underline: true,
        content: "[일반 혈액 검사]\n- 일반 혈액 검사상 빈혈은 없으며, 백혈구 및 혈소판 수치도 특별한 이상은 없습니다.",
      },
    ],
  },
  김모아202411042: {
    imageSet: [
      { id: uuidv4(), x: 60, y: 110, width: 70, height: 70, url: "/icons/medicalReport.png" },
      { id: uuidv4(), x: 60, y: 380, width: 70, height: 70, url: "/icons/heartbeat.png" },
    ],
    divSet: [{ id: uuidv4(), x: 45, y: 90, width: 700, height: 3, color: "blue" }],
    tableSet: [
      {
        id: uuidv4(),
        x: 60,
        y: 210,
        width: 670,
        height: 120,
        data: [
          {
            row: 1,
            cells: [
              { col: 1, content: "검사항목" },
              { col: 2, content: "참고치" },
              { col: 3, content: "2023-01-04" },
              { col: 4, content: "2021-10-13" },
              { col: 5, content: "2019-05-20" },
            ],
          },
          {
            row: 2,
            cells: [
              { col: 1, content: "신장 cm" },
              { col: 2, content: "0~0" },
              { col: 3, content: "160.4" },
              { col: 4, content: "159.5" },
              { col: 5, content: "160.3" },
            ],
          },
          {
            row: 3,
            cells: [
              { col: 1, content: "체중" },
              { col: 2, content: "0~0" },
              { col: 3, content: "62.4" },
              { col: 4, content: "60.3" },
              { col: 5, content: "62.7" },
            ],
          },
          {
            row: 4,
            cells: [
              { col: 1, content: "체질량지수" },
              { col: 2, content: "18.5~22.9" },
              { col: 3, content: "24.3" },
              { col: 4, content: "23.7" },
              { col: 5, content: "24.4" },
            ],
          },
          {
            row: 5,
            cells: [
              { col: 1, content: "허리 둘레" },
              { col: 2, content: "0~84" },
              { col: 3, content: "84.9" },
              { col: 4, content: "82.2" },
              { col: 5, content: "89.6" },
            ],
          },
        ],
        rows: 5,
        columns: 5,
      },
      {
        id: uuidv4(),
        x: 60,
        y: 470,
        width: 670,
        height: 100,
        data: [
          {
            row: 1,
            cells: [
              { col: 1, content: "검사항목" },
              { col: 2, content: "참고치" },
              { col: 3, content: "2023-01-04" },
              { col: 4, content: "2021-10-13" },
              { col: 5, content: "2019-05-20" },
            ],
          },
          {
            row: 2,
            cells: [
              { col: 1, content: "최대혈압" },
              { col: 2, content: "91~119" },
              { col: 3, content: "107" },
              { col: 4, content: "103" },
              { col: 5, content: "110" },
            ],
          },
          {
            row: 3,
            cells: [
              { col: 1, content: "최소혈압" },
              { col: 2, content: "61~79" },
              { col: 3, content: "54" },
              { col: 4, content: "66" },
              { col: 5, content: "68" },
            ],
          },
          {
            row: 4,
            cells: [
              { col: 1, content: "맥박" },
              { col: 2, content: "60~100" },
              { col: 3, content: "72" },
              { col: 4, content: "71" },
              { col: 5, content: "73" },
            ],
          },
        ],
        rows: 4,
        columns: 5,
      },
    ],
    textareaSet: [
      {
        id: uuidv4(),
        x: 195,
        y: 60,
        width: 155,
        height: 30,
        placeholder: "Enter text",
        underline: true,
        content: "등록번호 01814444",
      },
      {
        id: uuidv4(),
        x: 430,
        y: 60,
        width: 130,
        height: 30,
        placeholder: "Enter text",
        underline: true,
        content: "일자 2024.05.12",
      },
      {
        id: uuidv4(),
        x: 650,
        y: 60,
        width: 120,
        height: 30,
        placeholder: "Enter text",
        underline: true,
        content: "성명 김모아",
      },

      {
        id: uuidv4(),
        x: 140,
        y: 130,
        width: 100,
        height: 70,
        placeholder: "Enter text",
        underline: true,
        content: "신체계측 및\n체성분",
      },
      {
        id: uuidv4(),
        x: 240,
        y: 110,
        width: 630,
        height: 90,
        placeholder: "Enter text",
        underline: true,
        content:
          "체성분검사, 키와 몸무게 및 체질량 지수를 계산하여 저체중과 비만 여부를\n알아보고, 허리둘레를 측정하여 복부비만 여부와 근육량 등을 알 수 있습니다.\n\n저체중:18.5미만 정상:18.5~23 과체중:23~25 비만:25~30 고도비만:30이상",
      },

      {
        id: uuidv4(),
        x: 150,
        y: 405,
        width: 100,
        height: 70,
        placeholder: "Enter text",
        underline: true,
        content: "혈압",
      },
      {
        id: uuidv4(),
        x: 240,
        y: 390,
        width: 490,
        height: 90,
        placeholder: "Enter text",
        underline: true,
        content:
          "안정 상태에서 수축기와 이완기의 혈압을 측정한 값으로 고혈압은 140/90mmHg 이상을 말하며, 치료와 예방을 위해 염분 섭취를 줄이고 규칙적인 운동 및 약물 요법이 필요합니다.",
      },
    ],
  },
};
